version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: alvinkigen97!
    volumes:
      - /srv/docker/data/mongo/db:/data/db
    networks:
      - mongo_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8092:8081"   # Access at http://YOUR_VPS_IP:8092
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:alvinkigen97!@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: "true"
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
    depends_on:
      - mongo
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge
